# TODO naming convention of basically everything
# TODO put copyright header on this lib
# double check globals, can prob abstract away many things
# TODO consider putting all the letters in their own class/file/seperate files
# TODO rewrite space as not just offset -- Why did i say this?
# TODO optional: M117 Printing...;Put printing message on LCD screen

import math
import time
from os import rename, remove


class ttg:
    def __init__(self, text, size, rotation, method, feedRate):
        # set basic passed args
        self.text = text
        self.size = size
        self.rotation = rotation
        self.method = method
        self.feedRate = str(feedRate)

        # set global class vars
        self.rotationNeeded = False
        self.readyForReturn = False
        self.operations = []
        self.currentXOffset = 0
        self.parsed = False
        self.verts = []

        # set defualts commands, TODO have function thats toGcode with custom commands
        self.offCmd = "M5"
        self.onCmd = "M3"
        self.fastCmd = "G0"
        self.slowCmd = "G1"

        # check if the user has specified a positive or negative rotation
        if self.rotation != 0:
            self.rotationNeeded = True

    def finalize(self):
        finalOperations = []

        for point in self.operations:
            if type(point) is tuple:
                originX = 0
                originY = 0
                newpointX = (
                    originX
                    + math.cos(self.rotation) * (point[0] - originX)
                    - math.sin(self.rotation) * (point[1] - originY)
                )
                newpointY = (
                    originY
                    + math.sin(self.rotation) * (point[0] - originX)
                    + math.cos(self.rotation) * (point[1] - originY)
                )
                newpoint = (newpointX, newpointY)
                finalOperations.append(newpoint)
            elif isinstance(point, str):
                finalOperations.append(point)

        # replace placeholder string commands with GCODE commands
        for count, command in enumerate(finalOperations):
            if command == "off":
                finalOperations[count] = self.offPowerCmd
            elif command == "on":
                finalOperations[count] = self.onPowerCmd
            elif command == "fast":
                finalOperations[count] = self.fastCmd
            elif command == "slow":
                finalOperations[count] = self.slowCmd

        if self.method == "visualize":
            return finalOperations

        elif self.method == "return" or self.method == "file":

            # initial preperation for file if user wants to output to gcode file
            if self.method == "file":
                try:
                    remove("output.txt")  # get rid of the temp output if it exists
                except:
                    pass
                gFile = open("output.txt", "a")  # create temp file

                # stamp temp file ;P TODO naming convention
                gFile.write(";generated by ttglib: Ryan Zmuda 2021\n")

            # Add neccessary header commands
            # EXPLANATION:
            # G90 - absolute positioning
            # G21 - metric values
            # G1 F[string of number] - feedrate
            finalOperations.insert(0, "G90")
            finalOperations.insert(0, "G21")
            finalOperations.insert(0, "G1 F" + self.feedRate)

            returnList = []
            lastMoveType = ""

            for command in finalOperations:
                currentCommand = ""

                if (
                    command == "G90"
                    or command == "G21"
                    or command == "G1 F" + self.feedRate
                ):
                    currentCommand = command

                if command == self.onPowerCmd:
                    currentCommand = self.onPowerCmd
                elif command == self.offPowerCmd:
                    currentCommand = self.offPowerCmd

                if command == self.slowCmd:
                    lastMoveType = "slow"
                    pass
                elif command == self.fastCmd:
                    lastMoveType = "slow"
                    pass

                if type(command) == tuple:
                    if lastMoveType == "slow":
                        currentCommand += self.slowCmd
                    elif lastMoveType == "fast":
                        currentCommand += self.fastCmd
                    # TODO text size
                    currentCommand += " X" + str(command[0])
                    currentCommand += " Y" + str(command[1])

                # TODO modify if statement for write to file
                if currentCommand != "":
                    returnList.append(currentCommand)

            if self.method == "return":
                return returnList

            elif self.method == "file":
                for line in returnList:
                    gFile.write(line + "\n")

                gFile.close()

                try:
                    remove("output.gcode")
                except:
                    pass

                rename(r"output.txt", r"output.gcode")

                return "output.gcode file generated successfully"

    def appendPoints(self, points):
        for point in points:
            self.operations.append(point)

    # LETTER FUNCTIONS

    def whiteSpace(self):
        self.currentXOffset += 4  # TODO check if this is right for character spaces

    #           .   .
    #       .           .
    #   .                   .
    #   .                   .
    #   .                   .
    #   .   .   .   .   .   .
    #   .                   .
    #   .                   .
    #   .                   .
    #   .                   .

    def a(self):  # TODO rewrite
        xOff = self.currentXOffset

        points = [
            "on",
            "slow",
            (0 + xOff, 0),
            (0 + xOff, 7),
            (1 + xOff, 8),
            (2 + xOff, 9),
            (3 + xOff, 9),
            (4 + xOff, 8),
            (5 + xOff, 7),
            (5 + xOff, 0),
            "off",
            "fast",
            (5 + xOff, 4),
            "on",
            "slow",
            (0 + xOff, 4),
            "off",
            "fast",
            (0 + xOff, 0),
        ]

        ttg.appendPoints(self, points)

    # TODO alright heres the requirements for letter verts
    # - every point has a tuple
    # - off on fast slow
    # - every list starts with on and ends with off

    #   .   .   .   .
    #   .               .
    #   .                   .
    #   .                   .
    #   .               .
    #   .   .   .   .
    #   .               .
    #   .                   .
    #   .                   .
    #   .   .   .   .   .

    def b(self):
        xOff = self.currentXOffset

        points = [
            "on",
            "slow",
            (0 + xOff, 0),
            (0 + xOff, 9),
            (3 + xOff, 9),
            (4 + xOff, 8),
            (5 + xOff, 7),
            (5 + xOff, 6),
            (4 + xOff, 5),
            (3 + xOff, 4),
            (0 + xOff, 4),
            "off",
            "fast",
            (3 + xOff, 4),
            "on",
            "slow",
            (4 + xOff, 3),
            (5 + xOff, 2),
            (5 + xOff, 1),
            (4 + xOff, 0),
            (0 + xOff, 0),
            "off",
            "fast",
        ]

        ttg.appendPoints(self, points)

    #       .   .   .   .
    #   .                   .
    #   .
    #   .
    #   .
    #   .
    #   .
    #   .
    #   .                   .
    #       .   .   .   .

    def c(self):
        xOff = self.currentXOffset

        points = [
            "off",
            "fast",
            (5 + xOff, 1),
            "on",
            "slow",
            (4 + xOff, 0),
            (1 + xOff, 0),
            (0 + xOff, 1),
            (0 + xOff, 8),
            (1 + xOff, 9),
            (4 + xOff, 9),
            (5 + xOff, 8),
            "off",
            "fast",
            (0 + xOff, 0),
        ]

        ttg.appendPoints(self, points)

    #   .   .   .   .
    #   .               .
    #   .                   .
    #   .                   .
    #   .                   .
    #   .                   .
    #   .                   .
    #   .                   .
    #   .               .
    #   .   .   .   .

    def d(self):
        xOff = self.currentXOffset

        points = [
            "on",
            "slow",
            (0 + xOff, 9),
            (3 + xOff, 9),
            (4 + xOff, 8),
            (5 + xOff, 7),
            (5 + xOff, 2),
            (4 + xOff, 1),
            (3 + xOff, 0),
            (0 + xOff, 0),
            "off",
            "fast",
        ]

        ttg.appendPoints(self, points)

    #   .   .   .   .   .   .
    #   .
    #   .
    #   .
    #   .   .   .   .   .   .
    #   .
    #   .
    #   .
    #   .
    #   .   .   .   .   .   .

    def e(self):
        xOff = self.currentXOffset

        points = [
            "on",
            "slow",
            (0 + xOff, 9),
            (5 + xOff, 9),
            "off",
            "fast",
            (5 + xOff, 5),
            "on",
            "slow",
            (0 + xOff, 5),
            "off",
            "fast",
            (5 + xOff, 0),
            "on",
            "slow",
            (0 + xOff, 0),
            "off",
            "fast",
        ]

        ttg.appendPoints(self, points)

    #   .   .   .   .   .   .
    #   .
    #   .
    #   .
    #   .
    #   .   .   .   .   .   .
    #   .
    #   .
    #   .
    #   .

    def f(self):
        xOff = self.currentXOffset

        points = [
            "on",
            "slow",
            (0 + xOff, 9),
            (5 + xOff, 9),
            "off",
            "fast",
            (5 + xOff, 5),
            "on",
            "slow",
            (0 + xOff, 5),
            "off",
            "fast",
            (0 + xOff, 0),
        ]

        ttg.appendPoints(self, points)

    #       .   .   .   .
    #   .                   .
    #   .
    #   .
    #   .
    #   .               .   .
    #   .                   .
    #   .                   .
    #   .                   .
    #       .   .   .   .

    def g(self):
        xOff = self.currentXOffset

        points = [
            "off",
            "fast",
            (5 + xOff, 8),
            "on",
            "slow",
            (4 + xOff, 9),
            (1 + xOff, 9),
            (0 + xOff, 8),
            (0 + xOff, 1),
            (1 + xOff, 0),
            (4 + xOff, 0),
            (5 + xOff, 1),
            (5 + xOff, 4),
            (4 + xOff, 4),
            "off",
            "fast",
            (0 + xOff, 0),
        ]

        ttg.appendPoints(self, points)

    #       .   .   .   .
    #   .                   .
    #   .
    #   .
    #   .
    #   .               .   .
    #   .                   .
    #   .                   .
    #   .                   .
    #       .   .   .   .

    def h(self):
        xOff = self.currentXOffset

        points = [
            "off",
            "fast",
            (5 + xOff, 8),
            "on",
            "slow",
            (4 + xOff, 9),
            (1 + xOff, 9),
            (0 + xOff, 8),
            (0 + xOff, 1),
            (1 + xOff, 0),
            (4 + xOff, 0),
            (5 + xOff, 1),
            (5 + xOff, 4),
            (4 + xOff, 4),
            "off",
            "fast",
            (0 + xOff, 0),
        ]

        ttg.appendPoints(self, points)

    #   .   .   .   .   .
    #           .
    #           .
    #           .
    #           .
    #           .
    #           .
    #           .
    #           .
    #   .   .   .   .   .

    def i(self):
        xOff = self.currentXOffset

        points = [
            "on",
            "slow",
            (4 + xOff, 0),
            "off",
            "fast",
            (4 + xOff, 9),
            "on",
            "slow",
            (0 + xOff, 9),
            "off",
            "fast",
            (2 + xOff, 9),
            "on",
            "slow",
            (2 + xOff, 0),
            "off",
            "fast",
            (0 + xOff, 0),
        ]

        ttg.appendPoints(self, points)

    #   .   .   .   .   .
    #           .
    #           .
    #           .
    #           .
    #           .
    #           .
    #           .
    #           .
    #   .   .

    def j(self):
        xOff = self.currentXOffset

        points = [
            "on",
            "slow",
            (1 + xOff, 0),
            (2 + xOff, 1),
            (2 + xOff, 9),
            (0 + xOff, 9),
            "off",
            "fast",
            (2 + xOff, 9),
            "on",
            "slow",
            (4 + xOff, 9),
            "off",
            "fast",
            (0 + xOff, 0),
        ]

        ttg.appendPoints(self, points)

    #   .                   .
    #   .                   .
    #   .                   .
    #   .               .
    #   .           .
    #   .   .   .
    #   .           .
    #   .               .
    #   .                   .
    #   .                   .

    def k(self):
        xOff = self.currentXOffset

        points = [
            "on",
            "slow",
            (0 + xOff, 9),
            "off",
            "fast",
            (5 + xOff, 9),
            "on",
            "slow",
            (5 + xOff, 7),
            (4 + xOff, 6),
            (3 + xOff, 5),
            (2 + xOff, 4),
            (1 + xOff, 4),
            (2 + xOff, 4),
            (3 + xOff, 3),
            (4 + xOff, 2),
            (5 + xOff, 1),
            (5 + xOff, 0),
            "off",
            "fast",
            (0 + xOff, 0),
        ]

        ttg.appendPoints(self, points)

    #   .            
    #   .            
    #   .            
    #   .        
    #   .    
    #   .
    #   .    
    #   .        
    #   .            
    #   .   .   .   .   .   .

    def l(self):
        xOff = self.currentXOffset

        points = [
            (0 + xOff, 9),
            "on",
            "slow",
            (0 + xOff, 0),
            (5 + xOff, 0),
            "off",
            "fast",
            (0 + xOff, 0),
        ]

        ttg.appendPoints(self, points)

    #   .                       .            
    #   .   .               .   .            
    #   .       .       .       .            
    #   .           .           .        
    #   .           .           .    
    #   .                       .
    #   .                       .    
    #   .                       .                 
    #   .                       .                       
    #   .                       .           

    def m(self):
        xOff = self.currentXOffset

        points = [
            "on",
            "slow",
            (0 + xOff, 9),
            (1 + xOff, 8),
            (2 + xOff, 7),
            (3 + xOff, 6),
            (3 + xOff, 5),
            (3 + xOff, 6),
            (4 + xOff, 7),
            (5 + xOff, 8),
            (6 + xOff, 9),
            (6 + xOff, 0),
            "off",
            "fast",
            (0 + xOff, 0),
        ]

        ttg.appendPoints(self, points)

    #   .                   . APROXIMATE, letting the cnc handle this movement
    #   . .                 .
    #   .   .               .
    #   .      .            .
    #   .                   .
    #   .        .          .
    #   .                   .
    #   .          .        .
    #   .             .     .
    #   .                .  .      

    def n(self):
        xOff = self.currentXOffset

        points = [
            "on",
            "slow",
            (0 + xOff, 9),
            (5 + xOff, 0),
            (5 + xOff, 9),
            "off",
            "fast",
            (0 + xOff, 0),
        ]

        ttg.appendPoints(self, points)

    #       .   .   .   .
    #   .                   .
    #   .                   .
    #   .                   .
    #   .                   .
    #   .                   .
    #   .                   .
    #   .                   .
    #   .                   .
    #       .   .   .   .     

    def o(self):
        xOff = self.currentXOffset

        points = [
            (0 + xOff, 1),
            "on",
            "slow",
            (0 + xOff, 8),
            (1 + xOff, 9),
            (4 + xOff, 9),
            (5 + xOff, 8),
            (5 + xOff, 1),
            (4 + xOff, 0),
            (1 + xOff, 0),
            "off",
            "fast",
            (0 + xOff, 0),
        ]

        ttg.appendPoints(self, points)

    #       .   .   .   .
    #   .                   .
    #   .                   .
    #   .                   .
    #   .                   .
    #   .   .   .   .   .
    #   .
    #   .
    #   .
    #   .

    def p(self):
        xOff = self.currentXOffset

        points = [
            "on",
            "slow",
            (0 + xOff, 8),
            (1 + xOff, 9),
            (4 + xOff, 9),
            (5 + xOff, 8),
            (5 + xOff, 5),
            (4 + xOff, 4),
            (0 + xOff, 4),
            "off",
            "fast",
            (0 + xOff, 0),
        ]

        ttg.appendPoints(self, points)

    #       .   .   .   .
    #   .                   .
    #   .                   .
    #   .                   .
    #   .                   .
    #   .                   .
    #   .                   .
    #   .                   .
    #   .               .
    #       .   .   .       .

    def q(self):
        xOff = self.currentXOffset

        points = [
            (0 + xOff, 1),
            "on",
            "slow",
            (0 + xOff, 8),
            (1 + xOff, 9),
            (4 + xOff, 9),
            (5 + xOff, 8),
            (5 + xOff, 2),
            (4 + xOff, 1),
            (5 + xOff, 0),
            "off",
            "fast",
            (3 + xOff, 0),
            "on",
            "slow",
            (1 + xOff, 0),
            "off",
            "fast",
            (0 + xOff, 0),
        ]

        ttg.appendPoints(self, points)

    #       .   .   .
    #   .               .
    #   .                   .
    #   .                   .
    #   .               .
    #   .   .   .   .   
    #   .               .
    #   .                   .
    #   .                   .
    #   .                   .

    def r(self):
        xOff = self.currentXOffset

        points = [
            "on",
            "slow",
            (0 + xOff, 8),
            (1 + xOff, 9),
            (3 + xOff, 9),
            (4 + xOff, 8),
            (5 + xOff, 7),
            (5 + xOff, 6),
            (4 + xOff, 5),
            (3 + xOff, 4),
            (0 + xOff, 4),
            "off",
            "fast",
            (3 + xOff, 4),
            "on",
            "slow",
            (4 + xOff, 3),
            (5 + xOff, 2),
            (5 + xOff, 0),
            "off",
            "fast",
            (0 + xOff, 0),
        ]

        ttg.appendPoints(self, points)

    # FOOTER

    # get and call functions for letter in given text and append them to queue
    def collectCharacters(self):
        for char in self.text:
            if char == " ":
                ttg.whiteSpace(self)
                self.currentXOffset += 8

            if char == "a" or char == "A":
                ttg.a(self)
                self.currentXOffset += 8

            if char == "b" or char == "B":
                ttg.b(self)
                self.currentXOffset += 8

            if char == "c" or char == "C":
                ttg.c(self)
                self.currentXOffset += 8

            if char == "d" or char == "D":
                ttg.d(self)
                self.currentXOffset += 8

            if char == "e" or char == "E":
                ttg.e(self)
                self.currentXOffset += 8

            if char == "f" or char == "F":
                ttg.f(self)
                self.currentXOffset += 8

            if char == "g" or char == "G":
                ttg.g(self)
                self.currentXOffset += 8

            if char == "h" or char == "H":
                ttg.h(self)
                self.currentXOffset += 8

            if char == "i" or char == "I":
                ttg.i(self)
                self.currentXOffset += 7

            if char == "j" or char == "J":
                ttg.j(self)
                self.currentXOffset += 7

            if char == "k" or char == "K":
                ttg.k(self)
                self.currentXOffset += 8

            if char == "l" or char == "L":
                ttg.l(self)
                self.currentXOffset += 8

            if char == "m" or char == "M":
                ttg.m(self)
                self.currentXOffset += 8

            if char == "n" or char == "N":
                ttg.n(self)
                self.currentXOffset += 8

            if char == "o" or char == "O":
                ttg.o(self)
                self.currentXOffset += 8

            if char == "p" or char == "P":
                ttg.p(self)
                self.currentXOffset += 8

            if char == "q" or char == "Q":
                ttg.q(self)
                self.currentXOffset += 8

            if char == "r" or char == "R":
                ttg.r(self)
                self.currentXOffset += 8

            if char == "s" or char == "S":
                ttg.s(self)
                self.currentXOffset += 8

            if char == "t" or char == "T":
                ttg.t(self)
                self.currentXOffset += 8

            if char == "u" or char == "U":
                ttg.u(self)
                self.currentXOffset += 8

            if char == "v" or char == "V":
                ttg.v(self)
                self.currentXOffset += 8

            if char == "w" or char == "W":
                ttg.w(self)
                self.currentXOffset += 8

            if char == "x" or char == "X":
                ttg.x(self)
                self.currentXOffset += 8

            if char == "y" or char == "Y":
                ttg.y(self)
                self.currentXOffset += 8

            if char == "z" or char == "Z":
                ttg.z(self)
                self.currentXOffset += 8

            if char == "1"
                ttg.one(self)
                self.currentXOffset += 8
            
            if char == "2"
                ttg.two(self)
                self.currentXOffset += 8

            if char == "3"
                ttg.three(self)
                self.currentXOffset += 8

            if char == "4"
                ttg.four(self)
                self.currentXOffset += 8

            if char == "5"
                ttg.five(self)
                self.currentXOffset += 8

            if char == "6"
                ttg.six(self)
                self.currentXOffset += 8

            if char == "7"
                ttg.seven(self)
                self.currentXOffset += 8

            if char == "8"
                ttg.eight(self)
                self.currentXOffset += 8

            if char == "9"
                ttg.nine(self)
                self.currentXOffset += 8

            if char == "0"
                ttg.zero(self)
                self.currentXOffset += 8

        return ttg.finalize(self)

    def encode(self):
        if self.readyForReturn and self.method == "visualize":
            return self.verts

        elif not self.readyForReturn:
            return ttg.collectCharacters(self)

    def toGcode(self, onPower, offPower, fast, slow):
        self.onPowerCmd = onPower
        self.offPowerCmd = offPower
        self.fastCmd = fast
        self.slowCmd = slow

        return ttg.encode(self)